baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: '2Good Coverband'
primary: true
siteGroup: 837418b5-ce83-430e-a287-110a0feb154a # 2Good Coverband
sortOrder: 1
