dateModified: 1725344514
email:
  fromEmail: nixgabriel92@gmail.com
  fromName: '2Good Coverband'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    009b5c9f-ce29-4677-ab87-750ee38f3666: '2Good Coverband' # 2Good Coverband
    837418b5-ce83-430e-a287-110a0feb154a: '2Good Coverband' # 2Good Coverband
system:
  edition: solo
  live: true
  name: '2Good Coverband'
  schemaVersion: 5.3.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
